### ISSUE TITLE
code-tracing

### ISSUE THREAD

**Issue by s0i37** [gaasedelen/lighthouse#11]
Hello.
Your plugin is awesome! DBI is better that breakpoint tracing...
I have one question. Do you know anything free solutions for code-trace analys/visualisation (not coverage) with all registers and memory states??
For example REVEN AXION (https://www.youtube.com/watch?v=5WNRplDPf5s) but his price is around 30k$/host. Or another example - QIRA, but it is for small-linux applications only...
I think, getting full-system code-trace for difficult applications via PANDA (https://github.com/panda-re/panda), but I dont know tools for analisys these traces.
(sorry for my bad english)

**Comment by gaasedelen** [comment]
QIRA is the best example of what meaningful trace exploration _should_ be like. It has a lot of problems, but the vision is there.

I can't speak on the value of Reven Axiom.

PANDA is probably the best public _Full System Tracing_ solution. But from my experience, it's really cumbersome to develop any sort of tools such as QIRA ontop of because poor mobility when navigating the trace. Using PANDA for the average userland application is probably also overkill.

There's a multitude of other userland 'tracing' frameworks, but few that offer any sort of visualization/interaction.

This is a space I've explored in the past and prototyped some tools in. It's a space I'd also like to revisit soon (but probably not with lighthouse.)
