### ISSUE TITLE
Extremely slow coverage loading

### ISSUE THREAD

**Issue by BlueAmulet** [gaasedelen/lighthouse#128]
One of my coverage files was taking hours to load. I found that it was spending a lot of time in the "orphan instruction" code checking if the address lies within db_metadata.instructions
https://github.com/gaasedelen/lighthouse/blob/develop/plugins/lighthouse/coverage.py#L577
After converting that instructions list to a set and using that instead, the coverage file would load within seconds like usual.

I do not know how the rest of the lighthouse code interacts with this list, hence raising an issue rather than a PR.

**Comment by gaasedelen** [comment]
Thank you for investigating this and taking the time to file an issue. It has been awhile since I have worked on any of my tools but am doing my best to go through the PRs / issues and merge what I can after all this time.

You are correct, it is not ok to simply switch the main `db_metadata.instructions` to a set for the general case as at least some parts of the codebase rely on the ordering that the list provides: https://github.com/gaasedelen/lighthouse/blob/0e0e08e564bd8e829a68480f826e975457c3e696/plugins/lighthouse/metadata.py#L154-L162

Back when I was actively developing lighthouse I had aggressively profiled and optimized lighthouse to squeeze as much as I could out of it being pure python. Orphan coverage is among one of the last things I had added, and I could see how this would be slow under extreme cases (a huge idb? with lots of 'orphan' coverage? lol)

A possible solution is to simply make a set instance of the instruction list while in this function. But that computation would have to happen for each coverage file loaded, which could be slow if loading 1000 coverage files. The alternative is having both the existing ordered list and a separate unordered set of all instructions in memory, all the time, which is also not ideal.

Or maybe I'll just make a helper to binary search the ordered list ¯\\\_(ツ)\_/¯

I'll have to think about this and try a few things. Thanks for the report.

**Comment by gaasedelen** [comment]
After reviewing the codebase, it's clear that I never actually used the instruction ordering for anything meaningful. Whatever I planned to use an ordered list for clearly never manifested (and, probably never will if I'm being honest).

At this point it's obviously for the best we switch it over to using a set. I didn't realize how damaging this became to loading coverage on larger databases, again it was probably one of the last 'features' I added, so it wasn't tested all that rigorously.

Thank you for filing the issue. It should be fixed as of 1b883377d6c94dc1f2489a079a1e68e0f6b4f619
