### ISSUE TITLE
Coverage window switches to floating mode when debug mode is used

### ISSUE THREAD

**Issue by agustingianni** [gaasedelen/lighthouse#16]
If you have a coverage window in your regular IDA view and you start a debugging session, the coverage window will switch to floating mode. It is not possible to move it back "inside" IDA.

My guess it that the "parent" window no longer exists and the coverage window is "orphan" hence it floats.

**Comment by gaasedelen** [comment]
Thanks for the report, I'll investigate this for v0.7

**Comment by gaasedelen** [comment]
I took a look at this today. What appears to be happening is that IDA is calling `saveState()` / `restoreState()` on the `QMainWindow` widget when switching between the debug/reversing states.

I can confirm that yes, the Coverage Overview widget pops out and floats when switching to the debugger. But I can re-dock the widget into the debug workspace by hovering and grabbing the dock prompt just beneath the window title. This is most likely happening because the Coverage Overview doesn't have known location/dock/layout in the debug workspace.

After docking it to the Debugger workspace once, the Coverage Overview positioning/dock state appears to get saved to the debugger workspace. Now when I start and stop the debugger multiple times, the coverage overview is docked in both states as one would expect.

I wrote a fix to try and force the Coverage Overview to get docked when entering the Debugger mode for the first time (for a given session). Any subsequent launches the Coverage Overview appears docked where it was last left (as one would expect).
