### ISSUE TITLE
do not support IDA7.0, indicting "Invalid Win32"

### ISSUE THREAD

**Issue by humblepride** [gaasedelen/lighthouse#18]
do not support IDA7.0, indicting "Invalid Win32"

**Comment by gaasedelen** [comment]
Lighthouse supports IDA 7. This sounds more like a problem with your python environment. I've only seen those types of errors when IDA is trying to load the interpreter of the wrong bitness, eg IDA 7.0 loading 32bit python.

Do you have a stack trace or anything I can work with? This issue is not actionable as-is.

**Comment by humblepride** [comment]
After checking binary of CodeCoverage.dll, i found a import dll named "pinvm", which i do not have. I downloaded Intel Pin Tool from its official website, and got pinvm.dll for ia32 and intel64. I copied pinvm.dll of intel64 into PATH, launch 64bit IDA, and it suggests: "dll initialize routine failed". while 32bit IDA still got "Invalid Win32". How should I fix this?

**Comment by gaasedelen** [comment]
The pintool (CodeCoverage*.dll) is not supposed to go in the IDA directory. It is supposed to be used separately, with pin. See the [usage](https://github.com/gaasedelen/lighthouse/tree/master/coverage/pin#usage) example.
