### ISSUE TITLE
not work in win7 sp1 x86 system

### ISSUE THREAD

**Issue by Lockmanxxx** [gaasedelen/lighthouse#19]
I am test on the windows 7 sp1 x86, the .log files looks like correct, but the lighthouse in IDA show the coverage is 0%

**Comment by gaasedelen** [comment]
What are you using to collect coverage? Sounds more than likely Lighthouse is failing to load the coverage because it can't identify the executable / library name.

If the name of the executable you collected coverage for doesn't match the executable that you used to generate the IDB, it will fail to load any coverage.

Eg, if you built the IDB with `foo.exe` but you collected coverage against `foo_patched.exe`, it will fail. You should rename your coverage target to whatever was use to generate the IDB.

This is an annoying limitation, but see if that works for you.

**Comment by Lockmanxxx** [comment]
Thanks a lot, I use dynamorio to collect coverage, I had get the error at lighthouse\parsers\drcov.py:_parse_drcov_header(self, f), it seems at the beginning of the log file, there may be some version string include char ":", but my log file of head is : 
Module loaded, test.exe
Module loaded, dynamorio.dll
Module loaded, MSVCR120D.dll
Module loaded, drsyms.dll
Module loaded, drwrap.dll
Module loaded, drreg.dll
Module loaded, drmgr.dll
Module loaded, drx.dll
Module loaded, winafl.dll
Module loaded, KERNELBASE.dll
Module loaded, USER32.dll
Module loaded, RPCRT4.dll
Module loaded, USP10.dll
Module loaded, OLEAUT32.dll
Module loaded, MSCTF.dll
......

So, the following code will out of range
version_line = f.readline().strip()
self.version = int(version_line.split(":")[1])

**Comment by gaasedelen** [comment]
Hmm, what version of DynamoRIO are you using? Is it possible for you to use a newer version?

I've at least tested it on DynamoRIO 6.2.x-7.x.x, but what you're using looks even older and I'm worried that (besides the blatant log format differences) the module information (address ranges) I need won't actually be present in the log.

**Comment by Lockmanxxx** [comment]
Yes, The problem is the version of DynamoRIO, I have modified the file content which the newer DynamoRIO create, the error is just happened at the beginning of the file content that is not match your code logic, Sorry to reply to you so long.
