### ISSUE TITLE
Is that load code coverage batch mean we can load mutil coverage file one time?

### ISSUE THREAD

**Issue by jinyu00** [gaasedelen/lighthouse#40]

**Comment by yrp604** [comment]
Yes, at least in windows you can select multiple by shift+click or control+click from the control coverage batch dialog.

**Comment by gaasedelen** [comment]
The 'Code coverage batch' menu option allows you to load and aggregate multiple coverage files into one lighthouse coverage item.

The 'Code coverage fifle' menu option allows you to load multiple coverage filles into multiple lighthouse coverage items.

As yrp said, you can shift+click, ctrl+click, or click & drag on windows (and other platforms) to select multiple files in the the file dialog.

Closing this because it is a question rather than an issue.
