### ISSUE TITLE
Incorrectly adds base address

### ISSUE THREAD

**Issue by JeffJerseyCow** [gaasedelen/lighthouse#55]
Lighthouse adds the base address within the function `rebase_blocks`, however in instances where static binaries have been traced the basic block addresses have already been offset by the base.

I've created the following patch to first check if the base address has been applied and only do so when it hasn't.

```
diff --git a/plugin/lighthouse/util/misc.py b/plugin/lighthouse/util/misc.py
index 99d9d92..bb859df 100644
--- a/plugin/lighthouse/util/misc.py
+++ b/plugin/lighthouse/util/misc.py
@@ -214,7 +214,13 @@ def rebase_blocks(base, basic_blocks):
     """
     Rebase a list of basic block offsets (offset, size) to the given imagebase.
     """
-    return map(lambda x: (base + x[0], x[1]), basic_blocks)
+    return_map = []
+    for x in basic_blocks:
+        if x[0] & base:
+            return_map.append((x[0], x[1]))
+        else:
+            return_map.append((base + x[0], x[1]))
+    return return_map
 
 def build_hitmap(data):
     """
```
Note that I initial tried this within map, but it lead to IDA crashing -- the for loop is much more stable.

I've been working on a project to convert qemu debugging information to drcov format and it is compatible with this patch.

**Comment by gaasedelen** [comment]
Sorry for the late response.

Currently, Lighthouse is designed only to expect coverage data in the form of relative offsets... not absolute addresses. Putting a 'fix' into this function is inappropriate because this function should never have been called to 'rebase' absolute addresses in the first place 😛  

I am closing this in favor of #41 where more general trace formats (such as absolute address traces) should be supported natively.
