### ISSUE TITLE
Add Python3 Support for Binary Ninja

### ISSUE THREAD

**Issue by 4T0r** [gaasedelen/lighthouse#58]

**Comment by gaasedelen** [comment]
This is a legitimate request and is on the roadmap for [future work](https://github.com/gaasedelen/lighthouse#future-work). 

Since binja support is super experimental, I don't plan to work on Python3 compatibility until Binary Ninja v1.2 (the UI update) is released. The update will allow me to remove the third party Qt bindings, opening the door towards 'official' support.

At that time, I will dedicate more resources to ensuring it works in all environments.

**Comment by 4T0r** [comment]
> This is a legitimate request and is on the roadmap for [future work](https://github.com/gaasedelen/lighthouse#future-work).
> 
> Since binja support is super experimental, I don't plan to work on Python3 compatibility until Binary Ninja v1.2 (the UI update) is released. The update will allow me to remove the third party Qt bindings, opening the door towards 'official' support.
> 
> At that time, I will dedicate more resources to ensuring it works in all environments.

Thanks

**Comment by gaasedelen** [comment]
This should now work thanks to #62

I have tested only it only on Windows, installing the py3 PyQt5 dep with a slightly different command:

```
pip3 install --target="%appdata%\Binary Ninja\plugins\Lib\site-packages" pyqt5
```

Don't be surprised if Py3 compatibility breaks between commits on the dev branch. I don't use Python 3 as my main interpreter so I won't be checking for regressions as often. I will try to ensure robustness closer to the next major release.
