### ISSUE TITLE
Block offset on 64 bits

### ISSUE THREAD

**Issue by cbayet** [gaasedelen/lighthouse#68]
Hi,

First, thanks for LightHouse, it's awesome.

I feel that this issue have already been more or less discussed, but never on the parsing side only.

I've developed my own LightHouse format coverage dumper around the Unicorn Engine, and it's working great.

One of my target is a kernel that loads at address 0, but the .text starts at an offset like 0x0000842000000000.
So the offset between the start of my module and my basic blocks cannot be contained on the 32 bits of the "start" field of the "_bb_entry_t" structure.

```
       typedef struct _bb_entry_t {
            uint   start;      /* offset of bb start from the image base */
            ushort size;
            ushort mod_id;
        } bb_entry_t;
```

Do you think LightHouse should support this on the parsing side ?
I think it should, and the patch should not be too complicated.

We could add a new field to the header of the BB Table, something like "Version" like in the Module Table header.
And the version 2 of this header would use a wider structure with a uint64_t as start.

If you think this is fine I can try to do a pull request.

An other way is to have a new field in the module table header that takes an offset to add to the image base.
Actually i've just noticed the version 4 of the header already support an "offset" field in the declaration of a module, but I didn't see the offset used anywhere. Maybe still in development ? Or maybe I completely missed something ?

Thanks for the help !

**Comment by gaasedelen** [comment]
Thank you for the kind words.

This issue has actually kind of been discussed recently, specifically in issue #54. The request was almost identical, but I think they were more or less storing absolute addresses ... which is basically what is happening here too.

Originally, I wrote the drcov parser to parse drcov files produced by DynamoRIO. The unfortunate consequence of that is that everyone has started making their custom binary instrumentation tooling produce drcov-like coverage files. Oops... I didn't intend to standardize it as a coverage format!

The C-structure that you cited is what I copied (for reference) from the Drcov/DynamoRIO source. The reason why I am so hesitant to integrate a change like this is because now we are technically diverging from the official DynamoRIO/Drcov format.

The solution to this is supposed to be custom coverage log parsers (see https://github.com/gaasedelen/lighthouse/issues/41). This is actually available on the develop branch, but might still be a little unstable.  There should be two additional (and simpler) supported coverage file formats. Sample logs should be in the 'testcase' folder. Adding new formats should be relatively easy too.

Would this be suitable? How hard would it be to convert your tooling to output a '[mod+off](https://github.com/gaasedelen/lighthouse/issues/41#issuecomment-432903069)' format going forward? Or maybe even just an address trace?

**Comment by gaasedelen** [comment]
Past that, most of Lighthouse is fairly well documented. Making a local patch for your stuff might be the easiest way to go for now until I get around to finishing the work on dev (maybe this summer?).

I can't promise I would accept a PR for this issue.

Thanks!

**Comment by cbayet** [comment]
Hi,

Thanks for the response :)
I think the solution for additional coverage format is perfectly fine for me. 

I'll make a local patch for this particular case, and wait for the release of those additional formats, since it works already fine for most of my cases.

> How hard would it be to convert your tooling to output a 'mod+off' format going forward?

This won't be a problem ! The code to generate the drcov format is actually very concise and was easy to implement ;)

Thanks again !
