### ISSUE TITLE
Feature request: Hover & show trace covering block

### ISSUE THREAD

**Issue by 0vercl0k** [gaasedelen/lighthouse#8]
It would be great if when hovering a colored basic block, Lighthouse could display the name of at least one of the coverage files that is responsible for this block being hit (attribution)

**Comment by gaasedelen** [comment]
We've talked about this privately, but I'd like to leave something here for the public record. 

The applicable scenario here is when you're viewing the aggregate set of let's say 1000 coverage files and you want to know which one hit *THIS* block.

The problem is that when I compute the aggregate set, I flatten all the existing coverage bitmaps into one. The information or ability to do attribution from just an aggregate is not possible.

If you're viewing the aggregate with all the independent N coverage files still loaded into Lighthouse, I could loop through the loaded coverage sets and print the names of the coverage sets registering coverage data for that basic block (which should be instant).

There is no problem with this, but loading N number of coverage files can be memory intensive and won't scale to immense sets (hence, the point of batch mode).

Thanks for the request, I'll consider this for v0.7 :-)

**Comment by gaasedelen** [comment]
This feature is now available on dev for IDA Pro. Simply right-click any line in the graph/disas view and select 'Xrefs to coverage...'. Double-clicking one of these entries will switch to that coverage set.

![image](https://user-images.githubusercontent.com/9522648/55297060-f721fe00-53ef-11e9-85af-50fc72e1b8fa.png)

I will add the Binja abstractions for this feature once I refactor lighthouse to account for the newly released UI APIs.
