### ISSUE TITLE
Crashes IDA when installed.

### ISSUE THREAD

**Issue by DigiAngel** [gaasedelen/lighthouse#84]
Copied the lighthouse and lighthouse_plugin.py from plugins to my plugins dir.  Ida 7.4.191112.
![Annotation 2020-04-29 195930](https://user-images.githubusercontent.com/947191/80664753-cf6af280-8a54-11ea-85e1-cb5d738ca71d.jpg)

**Comment by gaasedelen** [comment]
Oh boy, that's bad.

Lighthouse doesn't really do much until you actually start trying to use it. So I assume its conflicting with some other installed plugin, or the system...

* What version of Python are you using?
* What other plugins do you have installed?
* What OS? (Windows 10?)

**Comment by DigiAngel** [comment]
Thanks for the quick response.  Python version is 3.8.1 64-bit, Windows version is 1909, no third party plugins installed.

**Comment by gaasedelen** [comment]
Ah, okay. I had a feeling you might be using Python 3.8. I have not officially tested on Python 3.8 with IDA 7.4 because, well, it has been problematic for both IDA an Binary Ninja.

I am pretty sure you are encountering this: https://www.hex-rays.com/blog/ida-7-4-and-python-3-8/

```
2. When trying to use PyQt, IDA crashes. Unfortunately, in 3.8 the layout of some internal Python structures have changed and SIP (the API bindings library used by PyQt) tries to access wrong data. Notably, this issue also affects Linux and Mac versions of IDAPython. If you are affected by this, please contact support for an updated build of sip module.
```

Please contact Hexrays support and get an updated SIP module for your 7.4 installation, or downgrade to Python 3.7/3.6

**Comment by DigiAngel** [comment]
Thanks I'll do the downgrade for now.
